steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
  - name: 'gcr.io/cloud-builders/npm'
    env: ['NPM_TOKEN=${_NPM_TOKEN}']
    args: ['publish']